# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'NewApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'

end
